name: difftrainerB
dependencies:
  - python=3.10
  - tk
  - tqdm
  - pyyaml
  - requests
  - pillow
  - click
  - h5py
  - matplotlib
  - "numpy<2.0.0"
  - "onnx~=1.16.0"
  - "scipy>=1.10.0"
  - tensorboard
  - tensorboardX
  - torchmetrics
  - pip
  - pip:
    - customtkinter
    - ctktooltip
    - ez-localizr
    - pyglet
    - "librosa<0.10.0"
    - "lightning~=2.1.0"
    - MonkeyType==23.3.0
    - "onnxsim~=0.4.36"
    - praat-parselmouth==0.4.3
    - pyworld==0.3.4